buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "jitpack"
            url = "https://jitpack.io"
        }
    }
    dependencies {
        classpath "com.github.voldeloom:voldeloom:2.5-SNAPSHOT"
    }
}

apply plugin: 'com.github.voldeloom.voldeloom'

version = "1.0.0"
group = "com.advancedtech"
archivesBaseName = "AdvancedTechEvolution"

sourceCompatibility = targetCompatibility = '1.8'
compileJava.options.encoding = 'UTF-8'

minecraft {
    version = "1.12.2"
}

repositories {
    mavenCentral()
}

dependencies {
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}